name: Dockerize application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Ceckout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mastermnb/icarus-dedicated-server:latest, mastermnb/icarus-dedicated-server:${{ github.run_number }}
